# Generated by Django 5.2.7 on 2025-10-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('text', models.TextField(max_length=5000)),
                ('mood', models.CharField(choices=[('content', 'Content'), ('melancholy', 'Melancholy'), ('sorrowful', 'Sorrowful'), ('grateful', 'Grateful'), ('energetic', 'Energetic'), ('positive', 'Positive'), ('motivated', 'Motivated'), ('tired', 'Tired'), ('depressive', 'Depressive')], max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=80)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=2000)),
                ('timestamp', models.TimeField()),
                ('room_id', models.IntegerField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='journal.journalentry')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='journal.journalentry')),
            ],
        ),
        migrations.AddField(
            model_name='journalentry',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.user'),
        ),
    ]
